services: 
  base:
    build:
      args:
        DOLIBARR_VERSION: ${DOLIBARR_VERSION:-latest}
        MEMCACHED_ENABLED: ${DOLIBARR_MEMCACHED_ENABLED:-false}
        XDEBUG_ENABLED: ${DOLIBARR_XDEBUG_ENABLED:-false}
      context: .
      tags:
        - &tags soli/dolibarr:${DOLIBARR_VERSION:-latest}${DOLIBARR_MEMCACHED_ENABLED:+-memcached}${DOLIBARR_XDEBUG_ENABLED:+-xdebug}
    env_file:
      - ./dolibarr-docker/env/dolibarr.env
    depends_on:
      - postgres
    environment:
      DOLI_ADMIN_LOGIN_FILE: /run/secrets/dolibarr-admin-user
      DOLI_ADMIN_PASSWORD_FILE: /run/secrets/dolibarr-admin-password
      DOLI_DB_PASSWORD_FILE: /run/secrets/postgres-password
      DOLI_DB_USER_FILE: /run/secrets/postgres-user
    image: *tags
    restart: unless-stopped
    secrets:
      - dolibarr-admin-password
      - dolibarr-admin-user
      - postgres-user
      - postgres-password
    volumes:
      - dolibarr-docs:/var/www/documents
      - dolibarr-custom:/var/www/html/custom
