services:
  dolibarr:
    environment:
      DOLI_URL_ROOT: "https://${DOLIBARR_HOSTNAME}"
    extends:
      file: ../compose.base.yaml
      service: base
    labels:
      traefik.enable: true
      traefik.http.routers.dolibarr.entrypoints: websecure
      traefik.http.routers.dolibarr.rule: "Host(`${DOLIBARR_HOSTNAME}`)"
      traefik.http.routers.dolibarr.tls.certresolver: myresolver
      traefik.http.services.dolibarr.loadbalancer.server.port: 80
    networks:
      - default
      - web

  postgres:
    environment:
      POSTGRES_DB: dolibarr
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_USER_FILE: /run/secrets/postgres-user
    image: postgres:alpine
    restart: unless-stopped
    secrets:
      - postgres-password
      - postgres-user
