services: 
  cron:
    environment:
      DOLI_CRON: 1
      DOLI_CRON_KEY_FILE: /run/secrets/dolibarr-cron-key
      DOLI_CRON_USER_FILE: /run/secrets/dolibarr-cron-user
    extends:
      file: ../compose.base.yaml
      service: base
    secrets:
      - dolibarr-cron-key
      - dolibarr-cron-user

  dolibarr:
    environment:
      DOLI_URL_ROOT: "https://${HOSTNAME}"
    extends:
      file: ../compose.base.yaml
      service: base
    labels:
      traefik.enable: true
      traefik.http.routers.dolibarr.entrypoints: websecure
      traefik.http.routers.dolibarr.rule: "Host(`${HOSTNAME}`)"
      traefik.http.routers.dolibarr.tls.certresolver: myresolver
      traefik.http.services.dolibarr.loadbalancer.server.port: 80
    networks:
      - default
      - web

  postgres:
    environment:
      POSTGRES_DB: dolibarr
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_USER_FILE: /run/secrets/postgres-user
    image: postgres:alpine
    restart: unless-stopped
    secrets:
      - postgres-password
      - postgres-user

networks:
  web:
    external: true

secrets:
  dolibarr-admin-password:
    file: ../.secrets/dolibarr_admin_password.secret
  dolibarr-admin-user:
    file: ../.secrets/dolibarr_admin_username.secret
  dolibarr-cron-key:
    file: ../.secrets/dolibarr_cron_key.secret
  dolibarr-cron-user:
    file: ../.secrets/dolibarr_cron_user.secret
  postgres-password:
    file: ../.secrets/postgres_password.secret
  postgres-user:
    file: ../.secrets/postgres_user.secret
