# Copyright (C) 2022-2024 Solution Libre
#
# This file is part of Dolibarr with Docker Compose.
#
# Dolibarr with Docker Compose is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Dolibarr with Docker Compose is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Dolibarr with Docker Compose.  If not, see <https://www.gnu.org/licenses/>.

services:
  dolibarr:
    environment:
      DOLI_URL_ROOT: "https://${DOLIBARR_HOSTNAME}"
    extends:
      file: ../compose.base.yaml
      service: base
    labels:
      traefik.enable: true
      traefik.http.routers.dolibarr.entrypoints: websecure
      traefik.http.routers.dolibarr.rule: "Host(`${DOLIBARR_HOSTNAME}`)"
      traefik.http.routers.dolibarr.tls.certresolver: myresolver
      traefik.http.services.dolibarr.loadbalancer.server.port: 80
    networks:
      - default
      - web

  postgres:
    environment:
      POSTGRES_DB: dolibarr
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_USER_FILE: /run/secrets/postgres-user
    image: postgres:alpine
    restart: unless-stopped
    secrets:
      - postgres-password
      - postgres-user
