# Copyright (C) 2023-2024 Solution Libre
#
# This file is part of Dolibarr with Docker Compose.
#
# Dolibarr with Docker Compose is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Dolibarr with Docker Compose is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Dolibarr with Docker Compose.  If not, see <https://www.gnu.org/licenses/>.

services: 
  base:
    build:
      args:
        DOLIBARR_VERSION: ${DOLIBARR_VERSION:-latest}
        MEMCACHED_ENABLED: ${DOLIBARR_MEMCACHED_ENABLED:-false}
        XDEBUG_ENABLED: ${DOLIBARR_XDEBUG_ENABLED:-false}
      context: .
      tags:
        - &tags soli/dolibarr:${DOLIBARR_VERSION:-latest}${DOLIBARR_MEMCACHED_ENABLED:+-memcached}${DOLIBARR_XDEBUG_ENABLED:+-xdebug}
    env_file:
      - ./dolibarr-docker/env/dolibarr.env
    depends_on:
      - postgres
    environment:
      DOLI_ADMIN_LOGIN_FILE: /run/secrets/dolibarr-admin-user
      DOLI_ADMIN_PASSWORD_FILE: /run/secrets/dolibarr-admin-password
      DOLI_DB_PASSWORD_FILE: /run/secrets/postgres-password
      DOLI_DB_USER_FILE: /run/secrets/postgres-user
    image: *tags
    restart: unless-stopped
    secrets:
      - dolibarr-admin-password
      - dolibarr-admin-user
      - postgres-user
      - postgres-password
    volumes:
      - dolibarr-docs:/var/www/documents
      - dolibarr-custom:/var/www/html/custom
