# Copyright (C) 2023-2024 Solution Libre
#
# This file is part of Dolibarr with Docker Compose.
#
# Dolibarr with Docker Compose is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Dolibarr with Docker Compose is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Dolibarr with Docker Compose.  If not, see <https://www.gnu.org/licenses/>.

include:
  - path: 
      - dolibarr-docker/compose.yaml
      - compose.dolibarr-docker.override.yaml

networks:
  web:
    external: true

secrets:
  dolibarr-admin-password:
    file: .secrets/dolibarr_admin_password.secret
  dolibarr-admin-user:
    file: .secrets/dolibarr_admin_username.secret
  dolibarr-cron-key:
    file: .secrets/dolibarr_cron_key.secret
  dolibarr-cron-user:
    file: .secrets/dolibarr_cron_user.secret
  postgres-password:
    file: .secrets/postgres_password.secret
  postgres-user:
    file: .secrets/postgres_user.secret

services:
  cron:
    environment:
      DOLI_CRON: 1
      DOLI_CRON_KEY_FILE: /run/secrets/dolibarr-cron-key
      DOLI_CRON_USER_FILE: /run/secrets/dolibarr-cron-user
    extends:
      file: compose.base.yaml
      service: base
    secrets:
      - dolibarr-cron-key
      - dolibarr-cron-user
  memcached:
    image: memcached:alpine
    profiles:
      - memcached
