version: '3'

services: 
  cron:
    env_file:
      - ./env/dolibarr.env
    environment:
      DOLI_CRON: 1
      DOLI_CRON_KEY: ${DOLI_CRON_KEY}
      DOLI_CRON_USER: ${DOLI_CRON_USER}
      DOLI_DB_USER_FILE: /run/secrets/mysql-user
      DOLI_DB_PASSWORD_FILE: /run/secrets/mysql-password
      DOLI_ADMIN_LOGIN_FILE: /run/secrets/dolibarr-admin-user
      DOLI_ADMIN_PASSWORD_FILE: /run/secrets/dolibarr-admin-password
    image: tuxgasy/dolibarr:latest
    restart: unless-stopped
    secrets:
      - dolibarr-admin-password
      - dolibarr-admin-user
      # - dolibarr-cron-key
      # - dolibarr-cron-user
      - mysql-user
      - mysql-password
    volumes:
      - dolibarr-docs:/var/www/documents
      - dolibarr-custom:/var/www/html/custom

  dolibarr:
    environment:
      DOLI_URL_ROOT: "https://${HOSTNAME}"
    labels:
      traefik.enable: 'true'
      traefik.http.routers.dolibarr.entrypoints: websecure
      traefik.http.routers.dolibarr.rule: "Host(`${HOSTNAME}`)"
      traefik.http.routers.dolibarr.tls.certresolver: myresolver
      traefik.http.services.dolibarr.loadbalancer.server.port: 80
    networks:
      - default
      - web
    restart: unless-stopped

  mysql:
    restart: unless-stopped

  smtpd:
    environment:
      RELAY_DOMAINS: ${SMTP_RELAY_DOMAINS}
      SMARTHOST_ADDRESS: ${SMTP_HOSTNAME}
      SMARTHOST_ALIASES: ${SMTP_ALIASES}
      SMARTHOST_PASSWORD_FILE: /run/secrets/smtpd-password
      SMARTHOST_PORT: ${SMTP_PORT}
      SMARTHOST_USER_FILE: /run/secrets/smtpd-user
    hostname: "smtpd.${HOSTNAME}"
    image: ixdotai/smtp
    restart: unless-stopped
    secrets:
      - smtpd-password
      - smtpd-user
    volumes:
      - ../docker-volumes/smtpd/_docker_additional_macros:/etc/exim4/_docker_additional_macros
      - ../docker-volumes/smtpd/exim4.conf.template:/etc/exim4/exim4.conf.template

networks:
  web:
    external: true

secrets:
  dolibarr-admin-password:
    file: ../.secrets/dolibarr_admin_password.secret
  dolibarr-admin-user:
    file: ../.secrets/dolibarr_admin_username.secret
  # dolibarr-cron-key:
  #   file: ../.secrets/dolibarr_cron_key.secret
  # dolibarr-cron-user:
  #   file: ../.secrets/dolibarr_cron_user.secret
  mysql-password:
    file: ../.secrets/mysql_password.secret
  mysql-user:
    file: ../.secrets/mysql_user.secret
  smtpd-password:
    file: ../.secrets/smtpd_password.secret
  smtpd-user:
    file: ../.secrets/smtpd_user.secret
