version: '3'

services: 
  cron:
    env_file:
      - ./env/dolibarr.env
    depends_on:
      - postgres
    environment:
      DOLI_CRON: 1
      DOLI_DB_USER_FILE: /run/secrets/postgres-user
      DOLI_DB_PASSWORD_FILE: /run/secrets/postgres-password
      DOLI_ADMIN_LOGIN_FILE: /run/secrets/dolibarr-admin-user
      DOLI_ADMIN_PASSWORD_FILE: /run/secrets/dolibarr-admin-password
    image: tuxgasy/dolibarr:latest
    restart: unless-stopped
    secrets:
      - dolibarr-admin-password
      - dolibarr-admin-user
      - dolibarr-cron-key
      - dolibarr-cron-user
      - postgres-user
      - postgres-password
    volumes:
      - dolibarr-docs:/var/www/documents
      - dolibarr-custom:/var/www/html/custom

  dolibarr:
    env_file:
      - ./env/dolibarr.env
    environment:
      DOLI_URL_ROOT: "https://${HOSTNAME}"
      DOLI_ADMIN_LOGIN_FILE: /run/secrets/dolibarr-admin-user
      DOLI_ADMIN_PASSWORD_FILE: /run/secrets/dolibarr-admin-password
      DOLI_DB_PASSWORD_FILE: /run/secrets/postgres-password
      DOLI_DB_USER_FILE: /run/secrets/postgres-user
    labels:
      traefik.enable: true
      traefik.http.routers.dolibarr.entrypoints: websecure
      traefik.http.routers.dolibarr.rule: "Host(`${HOSTNAME}`)"
      traefik.http.routers.dolibarr.tls.certresolver: myresolver
      traefik.http.services.dolibarr.loadbalancer.server.port: 80
    networks:
      - default
      - web
    restart: unless-stopped
    secrets:
      - dolibarr-admin-password
      - dolibarr-admin-user
      - postgres-password
      - postgres-user

  postgres:
    environment:
      POSTGRES_DB: dolibarr
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_USER_FILE: /run/secrets/postgres-user
    image: postgres:alpine
    restart: unless-stopped
    secrets:
      - postgres-password
      - postgres-user

networks:
  web:
    external: true

secrets:
  dolibarr-admin-password:
    file: ../.secrets/dolibarr_admin_password.secret
  dolibarr-admin-user:
    file: ../.secrets/dolibarr_admin_username.secret
  dolibarr-cron-key:
    file: ../.secrets/dolibarr_cron_key.secret
  dolibarr-cron-user:
    file: ../.secrets/dolibarr_cron_user.secret
  postgres-password:
    file: ../.secrets/postgres_password.secret
  postgres-user:
    file: ../.secrets/postgres_user.secret
